[package]
name = "nn_from_scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
mnist = "0.2"
ndarray = "0.15"

[lib]
path="src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "nn_from_scratch"